### PR TITLE
PKAR page changes

### PR DESCRIPTION
**Pull request by andre91a**
new pull request to merge #149 in production

### CODE REVIEW

**Comment by davidrapin** [comment]
@andre91a Ok I understand the problem: we do not merge branches in production directly, we merge the branch into preprod, then we need to trigger a release of the doc from the preprod branch.

**Comment by andre91a** [comment]
Ok but I think I've to create a new pull request to "preprod" cause I cannot modify this one

**Comment by davidrapin** [comment]
the changes are already in preprod: https://github.com/Linkurious/documentation/pull/149

**Comment by francescoinfante** [comment]
closing here, this is already merged to preprod

**Pull request closed without merging**
